### ISSUE TITLE
color change

### ISSUE THREAD

**Issue by DerTom1978** [ioBroker/ioBroker.vis-2-widgets-gauges#114]
Hi all,

where can I choose the color of the liquid in the water gauge?
where can I change the font color of the level?

BR
Tom

**Comment by GermanBluefox** [comment]
From 0.2.0
![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-gauges/assets/4582016/ba5be7e6-dbd3-4a84-831d-49ba7765f89d)

**Comment by Feuer-sturm** [comment]
@DerTom1978 please check the feedback of Bluefox.
Issue closed.

**Comment by DerTom1978** [comment]
Hi,
thank you very much.
Gradient I have found - thank you!
I can't find circle color and overlapping text color.
V 0.2.0

BR
Tom

**Comment by DerTom1978** [comment]
I have installed again on another (new) system. Now everything can be found as described.
Can finally be closed.
